= java-mavenmixin-docker
:_imagesdir: ./
:toc:


This module, for use within link:http://isis.apache.org[Apache Isis] applications, provides a link:https://github.com/odavid/maven-plugins[maven mixin] that can be used to package up a webapp as a Docker image using the `package` phase, and then to upload  that Docker image to a repository (eg docker hub) using the `deploy` phase.
It also disables the regular `maven-deploy-plugin` (so that the `<distributionManagement>` section is not required).

The appropriate configuration is included in a `<profile>`, but which is disabled by default; it can be enabled using a Maven property.



== How to Configure

To configure:

* copy and paste the following into either the `pom.xml` of the consuming module or (better still) the `pom.xml` of the top-level parent of the consuming module: +
+
[source,xml]
----
<properties>
    ...
    <mavenmixin-docker.version>0.0.2</mavenmixin-docker.version>
    <maven-deploy-plugin.version>2.8.1</maven-deploy-plugin.version>
    <docker-maven-plugin.version>0.4.13</docker-maven-plugin.version>
    <gmavenplus-plugin.version>1.5</gmavenplus-plugin.version>
    ...
</properties>
----
+
and: +
+
[source,xml]
----
<build>
    <pluginManagement>
        <plugins>
            ...
            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>${maven-deploy-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>${docker-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>${gmavenplus-plugin.version}</version>
            </plugin>
            ...
        </plugins>
    </pluginManagement>
</build>
----

* update the following property/ies in the `pom.xml` of the consuming webapp module (with `<packaging>war</packaging>`): +
+
[source,xml]
----
<properties>
    ...
    <docker-plugin.imageName>               <!--1-->
        XXX/${project.parent.artifactId}
    </docker-plugin.imageName>                 
    <docker-plugin.resource.include>        <!--2-->
        ${project.parent.artifactId}.war
    </docker-plugin.resource.include>
    <docker-plugin.releaseServerId>         <!--3-->
        docker-hub
    </docker-plugin.releaseServerId>                           
    <docker-plugin.releaseRegistryUrl>      <!--4-->
        https://index.docker.io/v1/
    </docker-plugin.releaseRegistryUrl>    
    <docker-plugin.snapshotServerId>        <!--5-->
        docker-hub
    </docker-plugin.snapshotServerId>                   
    <docker-plugin.snapshotRegistryUrl>     <!--6-->
        https://index.docker.io/v1/
    </docker-plugin.snapshotRegistryUrl> 
    ...
</properties>
----
<1> the name of the image to be created.
Change 'XXX' as required; for example if deploying to docker hub then 'XXX' will be the account name on docker hub.
<2> the WAR file to include within the image.
The idea is that the `Dockerfile` (below) copies this war file into the appropriate directory of the image.
If using the link:https://github.com/danhaywood/java-mavenmixin-jettywar[jettywar] mavenmixin then this could also be set to `${maven-war-plugin.warName}.war` 
<3> Optionally, the server to upload release images to (ie when the `project.version` is not a `-SNAPSHOT`)
This key is used to look up username/password credentials from `~/.m2/settings.xml`; see below for further details on this.
If not specified then "docker-hub" is assumed.
<4> Optionally, the corresponding URL to upload release images to.
Note that the URL is *not* looked up from `~/.m2/settings.xml`.
<5> Optionally, the server Id to upload snapshot images to (ie when the `project.version` _is_ a `-SNAPSHOT`)
If not specified then "docker-hub" is assumed.
<6> Optionally, the corresponding URL to upload snapshot images to.

* add the following to the `pom.xml` of the consuming webapp module: +
+
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.github.odavid.maven.plugins</groupId>
            <artifactId>mixin-maven-plugin</artifactId>
            <version>0.1-alpha-39</version>
            <extensions>true</extensions>
            <configuration>
                <mixins>
                    <mixin>
                        <groupId>com.danhaywood.mavenmixin</groupId>
                        <artifactId>docker</artifactId>
                        <version>${mavenmixin-docker.version}</version>
                    </mixin>
                </mixins>
            </configuration>
        </plugin>
    </plugins>
</build>
----

* if necessary, specify `src/main/resources` as a resource directory, with filtering (ie substitution of parameters) enabled:

+
[source,xml]
----
<build>
    <resources>
        <resource>
            <filtering>true</filtering>
            <directory>src/main/resources</directory>
        </resource>
        ...
    </resources>
    ...
</build>
----

* create a `Dockerfile` in `src/main/resources/docker`. +
+
For example: +
+
[source,xml]
----
FROM incodehq/tomcat
RUN rm -rf ${DEPLOYMENT_DIR}/ROOT
COPY ${docker-plugin.resource.include} ${DEPLOYMENT_DIR}/ROOT.war
EXPOSE 8080
----
+
The link:https://hub.docker.com/r/incodehq/tomcat/~/dockerfile/[`incodehq/tomcat`] base image exposes the `${DEPLOYMENT_DIR}` environment variable as the directory to deploy war files to.
The `${docker-plugin.resource.include}` property will be substituted with the value defined in the `pom.xml`.
You can of course add other configuration into the `Dockerfile`, see the link:https://docs.docker.com/engine/reference/builder/#/label[Dockerfile] reference for details.

* (if deploying to a docker registry), add the following to `~/.m2/settings.xml`:
+
[source,xml]
----
<servers>
    <server>
      <id>docker-hub</id>                               <!--1-->
      <username>danhaywood</username>                   <!--2-->
      <password>XXXXXXXX</password>                     
      <configuration>
        <email>dan@haywood-associates.co.uk</email>     <!--3-->
      </configuration>
    </server>
    ...
</servers>
----
<1> corresponds to the value of the `${docker-plugin.serverId}` property defined above
<2> username and password for the account defined for the repository (whose registry URL is defined by the `${docker-plugin.registryUrl}` property)
<3> corresponding email address, as described in the link:https://github.com/spotify/docker-maven-plugin#authenticating-with-private-registries[spotify docker plugin] README.





== How to use

To create the image file:

[source,bash]
----
mvn install -Dmavenmixin-docker
----

This will create an image and tagged it as both `latest` and using the consuming ``pom.xml``'s `project.version`.
The two tagged images will be visible using `docker images`.

To also upload (push) the image to the docker registry:

[source,bash]
----
mvn -pl webapp deploy -Dmavenmixin-docker
----

The `-pl webapp` runs the deploy in the `webapp` module (where the WAR file is built).

Where the image is uploaded to depends on the `project.version` of the consuming `pom.xml`:

* if the `project.version` is a `-SNAPSHOT`, then `docker-plugin.snapshotServerId` and `docker-plugin.snapshotRegistryUrl` properties will be used.

* if the `project.version` is _not_ a `-SNAPSHOT`, then `docker-plugin.releaseServerId` and `docker-plugin.releaseRegistryUrl` properties will be used.

This allows unstable snapshot images to be pushed to a different registry than the stable release images.

The above assumes that the `${docker-plugin.imageName}` property has been specified in the consuming `pom.xml`.
If necessary, though, that property can also be specified from the command line, eg:

[source,bash]
----
mvn deploy -Dmavenmixin-docker \
           -Ddocker-plugin.imageName=danhaywood/simpleapp
----

The underlying link:https://github.com/spotify/docker-maven-plugin#bind-docker-commands-to-maven-phases[docker-maven-plugin] also allows goals to be disabled using `-DskipDocker` and similar variants.



== How to consume

To run the image:

[source,bash]
----
docker run -d -p80:8080 XXX/imageName       
----

where `XXX/imageName` is the value of `${docker-plugin.imageName}` property specified in the consuming `pom.xml`.
It should then be possible to access the application from link:http://localhost[http://localhost].


As a slightly more complex example, we can run two docker images, one with postgres backend database and the other running the application itself:

[source,bash]
----
docker run --name postgres -d incodehq/postgres
----

and then:

[source,bash]
----
ISIS_OPTS=""
ISIS_OPTS="${ISIS_OPTS}isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionDriverName=org.postgresql.Driver"
ISIS_OPTS="${ISIS_OPTS}||isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionURL=jdbc:postgresql://db:5432/incodehq"
ISIS_OPTS="${ISIS_OPTS}||isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionUserName=incodehq"
ISIS_OPTS="${ISIS_OPTS}||isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionPassword=incodehq"

docker run --name imageName --link postgres:db -e ISIS_OPTS=$ISIS_OPTS -p 80:8080 -d XXX/imageName
----



Again, the application can be accessed from link:http://localhost[http://localhost].

NOTE: this requires that the postgres JDBC driver is part of the application being built.

== Known issues

None currently



== Change Log

* `0.0.3` - bind `build` goal to `install` phase rather than `package` phase.
Provide the capability to deploy snapshot images and release images to different registries.
* `0.0.2` - changed profile so is disabled by default
* `0.0.1` - first release




== Legal Stuff

=== License

[source]
----
Copyright 2016~date Dan Haywood

Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----



=== Dependencies

This mixin module relies on the link:https://github.com/odavid/maven-plugins[com.github.odavid.maven.plugins:mixin-maven-plugin], released under Apache License v2.0.



== Maven deploy notes

The module is deployed using Sonatype's OSS support (see
http://central.sonatype.org/pages/apache-maven.html[user guide] and http://www.danhaywood.com/2013/07/11/deploying-artifacts-to-maven-central-repo/[this blog post]).

The `release.sh` script automates the release process.
It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 0.0.3 \
              0.0.4-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where

* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the ``pgp-maven-plugin``'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master && git push origin 0.0.3
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue before trying again.
Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the `autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).
You may want to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].
